/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Resources = string[];

export interface GaroonPluginManifestJson {
  manifest_version: number;
  version: string;
  target_applications: ["ALL", ..."ALL"[]];
  impacted_applications: [
    (
      | "ALL"
      | "PORTAL"
      | "SPACE"
      | "BOOKMARKS"
      | "SCHEDULER"
      | "MESSAGES"
      | "BULLETIN_BOARD"
      | "CABINET"
      | "MEMO"
      | "PHONE_MESSAGES"
      | "TIMESHEET"
      | "ADDRESS_BOOK"
      | "EMAIL"
      | "WORKFLOW"
      | "MULTI_REPORT"
      | "PRESENCE_INDICATORS"
      | "FAVORITE"
      | "NOTIFICATIONS"
      | "RESPOND"
    ),
    ...(
      | "ALL"
      | "PORTAL"
      | "SPACE"
      | "BOOKMARKS"
      | "SCHEDULER"
      | "MESSAGES"
      | "BULLETIN_BOARD"
      | "CABINET"
      | "MEMO"
      | "PHONE_MESSAGES"
      | "TIMESHEET"
      | "ADDRESS_BOOK"
      | "EMAIL"
      | "WORKFLOW"
      | "MULTI_REPORT"
      | "PRESENCE_INDICATORS"
      | "FAVORITE"
      | "NOTIFICATIONS"
      | "RESPOND"
    )[]
  ];
  name: {
    ja?: string;
    en: string;
    zh?: string;
    "zh-tw"?: string;
  };
  description?: {
    ja?: string;
    en: string;
    zh?: string;
    "zh-tw"?: string;
  };
  /**
   * internal only
   */
  icon: string;
  homepage_url?: {
    ja?: string;
    en?: string;
    zh?: string;
    "zh-tw"?: string;
  };
  provider?: {
    ja?: {
      name: string;
      url: string;
    };
    en: {
      name: string;
      url: string;
    };
    zh?: {
      name: string;
      url: string;
    };
    "zh-tw"?: {
      name: string;
      url: string;
    };
  };
  desktop?: {
    js?: Resources;
    css?: Resources;
  };
  config?: {
    /**
     * internal only
     */
    html: string;
    js?: Resources;
    css?: Resources;
    required_params?: string[];
  };
}
